# Generated by Django 4.2 on 2023-04-12 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_comment2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment2',
            old_name='content',
            new_name='content2',
        ),
        migrations.RenameField(
            model_name='comment2',
            old_name='post',
            new_name='post2',
        ),
    ]
